version: "3.9"
services:
  node:
    image: box_dotnet
    volumes:
      - type: bind
        source: "./${FOLDER}"
        target: /app
    tty: true
    entrypoint: /bin/bash
    ports:
      - "3000:3000"
